### ISSUE TITLE
alpha priors

### ISSUE THREAD

**Issue by fifdick** [cozygene/BayesCCE#1]
Hi,

I have some questions for using the BayesCCE that i could not answer myself by going through the documentation provided in bayescce.m .
I am planning to use your tool on whole genome bisulfite sequencing data, where I derive the desired beta values from read coverage on each CpG position.
Now my question is, how do I derive the alpha prior that I need to provide to the function?
As I am working on brain tissue, I thought I could use data that you have referenced in your publication:
https://doi.org/10.4161/epi.23924 as a reference and derive the priors from this.
Is this possible and if so, how would I proceed? It is unclear for me how and if I need to use this https://github.com/tminka/fastfit package, as you recommended in your README.
Looking forward to your answer.

Fiona

**Comment by E-R** [comment]
Once you have a matrix with cell counts from external data (each row corresponds to an individual and each column corresponds to a cell type), to get alpha you just need to run the polya_fit function (using [fasfit](https://github.com/tminka/fastfit)) on it.
