### ISSUE TITLE
k, alpha, and matrix dimensions

### ISSUE THREAD

**Issue by petercombs** [cozygene/BayesCCE#2]
I'm testing out BayesCCE for deconvolving genotypes in several pooled samples, and on simulated data, I have a matrix 

    X --  5,000 site x 96 sample matrix of SNP abundances
      s.t. X = T*A, where
      T = 5,000 site x 25 strain genotypes, and 
      A = 25 strain x 96 sample strain abundances

If I'm understanding the documentation correctly, then my k=25.  However, I get an assertion error when I try:

    alpha = 4+randn(25)';
    [rest, mest, betaest, sites] = bayescce(X, covars, covars2, 25, 25, 2500, alpha)
    
which is the line:

    assert(size(alpha,2) == size(O,2))

Am I misunderstanding something here? If I replace the alpha with a 96-length vector, then I get a bunch of warning, around line 168 saying "X is rank deficient to within machine precision", then it fails on iteration 1 because the "Problem appears unbounded". 

Would appreciate help on how to proceed, thanks!

**Comment by E-R** [comment]
In your settings k=25 as you suggested.

Note that:
`alpha = 4+randn(25)';`
creates a 25 by 25 matrix, while alpha should be a 25-length vector in this case. Try the following instead:
`alpha = 4+randn(25,1);`

**Comment by petercombs** [comment]
Thanks! I feel pretty stupid, though it's been a while since I've done much work in Matlab.  randn(25,1) does fix the assertion issue, though I'm still having the issue with tons of "X is rank deficient to within machine precision", followed by "Problem appears unbounded", and the elements of R_est are all effectively identical. 

For the simulated test case I'm working on, I know that there aren't any meaningful covariates, so I just set

    covars = randn(96,1);
    covars2 = randn(96, 1); 

while the alpha values I got from a python port of the recommended fastfit (https://github.com/ericsuh/dirichlet).

**Comment by E-R** [comment]
Would you mind posting a full example of one of your simulations that reproduces the errors you refer to?

**Comment by petercombs** [comment]
It's the SimulateSNPs.py script here: https://github.com/petercombs/dicty/blob/pca/SimulateSNPs.py

    $ python SimulateSNPs.py --outdir test_5k -n 5 25 --num-samples 96 --num-snps 5000 
    $ cp -r test_5k ~/BayesCCE

Then in matlab:
    
    t = readtable('test_5k/strain_genotypes_25.tsv', 'FileType', 'text');
    a = readtable('test_5k/strain_abundances_25.tsv', 'FileType', 'text');
    T = table2array(t);
    T = T(2:end, 2:end); % strip off header row and column
    A = table2array(a);
    A = A(2:end, 2:end)';
    D = T * A;
    covars = randn(96, 1);
    covars2 = randn(96, 1);
    k = 25;
    [rest, mest, betaest, sites] = bayescce(D, covars, covars2, k, k, 2500, 4 + randn(k, 1));

Thanks for taking a look at it!

**Comment by E-R** [comment]
I could not get the warning "X is rank deficient to within machine precision" using your code.

As for the second warning, "Problem appears unbounded", see Matlab's documentation about this warning [here](https://www.mathworks.com/help/optim/ug/when-the-solver-fails.html#br44jjo). Basically, one of the possible reasons for this warning is related to a tolerance threshold of the optimization procedure. I verified that changing the objective limit tolerance indeed solves this issue. Specifically, I replaced the following line in bayescce.m:
`fmincon_options = optimset('GradObj','on','Display','iter','MaxIter',5000,'MaxFunEvals',30000);`
to include an updated objective limit tolerance:
`fmincon_options = optimset('GradObj','on','Display','iter','MaxIter',5000,'MaxFunEvals',30000,'ObjectiveLimit',-1e50);`
which resulted in a feasible solution without a warning.

BTW, note that k=25 represents a very detailed model and I suspect that it'll be hard to extract meaningful information from it using a relatively small sample size of 96.

**Comment by petercombs** [comment]
Thanks! Looks like that's getting me farther... I wonder if the "rank deficient" warning has to do with the version of Matlab—I'm running 2018b, and the cluster I'm on only has 2016b as the oldest, which is still newer than the 2015b that it was tested with. 

I am aware that k=25 is larger than most methylation studies seem to try for, and is actually smaller than what I plan to run in the future. I'm still waiting for my sequencing data to come back, but one of the things I'm hoping to get a sense of is how many samples I would need to get a reasonable breakdown of components. For the simulations, I know the ground truth, and will gradually introduce somewhat realistic noise to see how well the software does. Fortunately, this analysis is merely nice to have for the experiment I'm doing, rather than crucial, so if it can't be done, then it's not a huge loss.
